### ISSUE TITLE
Good first issue label

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/CoreNetKit#39]
What about to add "Good first issue" label to some issues?
I see a lot of new issues, I think we could delegate some of them to somebody who wanna be in our contributor's list.
What do you think @LastSprint ?

**Comment by LastSprint** [comment]
Delegated issueses marked "Help wanted", couse these not depend from library designing.
You should keep in mind that CoreNetKit is at redesign stage.

**Comment by ismetanin** [comment]
@LastSprint Oh, ok, thanks
